version: 0.0
os: linux
files:
  - source: /target/Spring-Hello-World.jar
    destination: /home/ec2-user/server
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/app_start
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/app_stop
      timeout: 300
      runas: root