version: 0.0
os: linux
files:
  - source: /target/Spring-Hello-World-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/server
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/app_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 300
      runas: root